break html into components
htmlacademy-ecmascript/1445957-cinemaddict-13 pull request #3
Opened 2020-11-18 09:20 UTC by anna9grace

2020-11-18 18:25 UTC, obzhorash requested changes

2020-11-18 18:25 UTC, obzhorash commented on public/index.html
>    <link rel="stylesheet" type="text/css" media="screen" href="/css/main.css" />
Необходимо поменять пути на относительные "./css/normalize.css".  
также для main.css и bundle.js

2020-11-18 18:25 UTC, obzhorash commented on src/main.js
> +const footerStats = document.querySelector(`.footer__statistics`);
Луче переименовать на что-то одинаковое ...Element или ...Node чтоб было понятно что это DOM элемент

2020-11-19 06:51 UTC, anna9grace commented on public/index.html
>    <link rel="stylesheet" type="text/css" media="screen" href="/css/main.css" />
поправила

2020-11-19 06:51 UTC, anna9grace commented on src/main.js
> +const footerStats = document.querySelector(`.footer__statistics`);
добавила к переменным "element"

2020-11-19 08:34 UTC, merged